"""PlatformIO pre-build hook: shared build counter.

Single source of truth = version.json at the project root. On every build
this script bumps the integer "build" counter once and then writes that SAME
number into three places so firmware, filesystem image and UI can never drift:

  1. main/build_info.h   -> compiled into the firmware (FW) and the UI.
  2. data/build.txt      -> packed into the SPIFFS "storage" image (FS),
                            which is flashed together with the app
                            (spiffs_create_partition_image ... FLASH_IN_PROJECT).

Because all artifacts are generated from one counter in one step and flashed
in one `pio run -t upload`, FW + FS + UI always carry the same build number.
At boot the firmware re-reads the FS number and compares it to the compiled
one, surfacing a mismatch on screen and in the log.
"""

Import("env")  # noqa: F821  (injected by PlatformIO/SCons)

import json
import os
import datetime

from SCons.Script import COMMAND_LINE_TARGETS

# Targets that must NOT bump the counter: filesystem/util operations that
# either reuse the last firmware build or don't produce firmware at all.
# Bumping here would silently push the FS/UI ahead of the flashed firmware.
NO_BUMP_TARGETS = {
    "flashfs", "uploadfs", "uploadfsota", "buildfs", "download_fs",
    "erase", "monitor", "clean", "cleanall", "size", "metrics",
    "compiledb", "menuconfig",
}

PROJECT_DIR = env.subst("$PROJECT_DIR")  # noqa: F821
VERSION_FILE = os.path.join(PROJECT_DIR, "version.json")
HEADER_FILE = os.path.join(PROJECT_DIR, "main", "build_info.h")
DATA_DIR = os.path.join(PROJECT_DIR, "data")
DATA_FILE = os.path.join(DATA_DIR, "build.txt")

DEFAULTS = {"version": "1.0", "patch": 0, "patch_base": "1.0", "build": 0}


def load_version():
    try:
        with open(VERSION_FILE, "r") as f:
            data = json.load(f)
        ver = str(data.get("version", DEFAULTS["version"]))
        return {
            "version":    ver,
            "patch":      int(data.get("patch", DEFAULTS["patch"])),
            "patch_base": str(data.get("patch_base", ver)),
            "build":      int(data.get("build", DEFAULTS["build"])),
        }
    except (IOError, ValueError, TypeError):
        return dict(DEFAULTS)


def save_version(data):
    with open(VERSION_FILE, "w") as f:
        json.dump(data, f, indent=2)
        f.write("\n")


def write_if_changed(path, content):
    """Avoid rewriting (and thus retriggering compiles) when unchanged."""
    try:
        with open(path, "r") as f:
            if f.read() == content:
                return
    except IOError:
        pass
    with open(path, "w") as f:
        f.write(content)


_targets = list(COMMAND_LINE_TARGETS)
# A plain `pio run` (no -t) has no command-line targets and builds firmware,
# so an empty list means "bump". Otherwise bump only if at least one target
# actually builds firmware.
should_bump = (not _targets) or any(t not in NO_BUMP_TARGETS for t in _targets)

data = load_version()
if should_bump:
    data["build"] += 1
    # Auto-count the patch within the current MAJOR.MINOR line (1.0.x), and
    # restart it at 0 whenever version.json "version" (major.minor) changes
    # -> bump "version" to "1.1" and the next build is 1.1.0, then 1.1.1, ...
    if data["patch_base"] != data["version"]:
        data["patch"] = 0
        data["patch_base"] = data["version"]
    else:
        data["patch"] += 1
    save_version(data)

build = data["build"]


# RELEASE version = MAJOR.MINOR (explicit in version.json "version") + an
# auto-incrementing PATCH that counts every firmware build within that line
# (1.0.0, 1.0.1, ...). Bump "version" to "1.1"/"2.0" to start a new line and the
# patch restarts at 0. DEYE_BUILD_NUMBER is a separate monotonic counter that
# ties FW + FS + UI together for the match check.
version = "%s.%d" % (data["version"], data["patch"])   # e.g. "1.0.1"
version_full = "v%s" % version
bar = "=" * 56

if not should_bump:
    # FS/util target only: reuse the artifacts from the last firmware build
    # so the filesystem image stays locked to the flashed firmware. Do NOT
    # rewrite the header (would force a needless recompile and a new
    # timestamp without a new number).
    print(bar)
    print("  Deye-Display build #%d   %s   (counter held, no firmware build)"
          % (build, version_full))
    print(bar)
else:
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    header = (
        "/* AUTO-GENERATED by scripts/build_number.py -- do NOT edit by hand.\n"
        " * Regenerated on every firmware build. Holds the shared build number\n"
        " * that ties the firmware, the SPIFFS asset image and the on-screen\n"
        " * UI together.\n"
        " */\n"
        "#pragma once\n"
        "\n"
        "#define DEYE_BUILD_NUMBER        %d\n"
        "#define DEYE_BUILD_VERSION       \"%s\"\n"
        "#define DEYE_BUILD_TIMESTAMP     \"%s\"\n"
        "#define DEYE_BUILD_VERSION_FULL  \"%s\"\n"
    ) % (build, version, timestamp, version_full)

    write_if_changed(HEADER_FILE, header)

    if not os.path.isdir(DATA_DIR):
        os.makedirs(DATA_DIR)

    # Line-based, parsed by atoi() in firmware (assets_fs.c). Line 1 = number.
    data_txt = "%d\n%s\n%s\n" % (build, version, timestamp)
    write_if_changed(DATA_FILE, data_txt)

    print(bar)
    print("  Deye-Display build #%d   %s   %s" % (build, version_full, timestamp))
    print(bar)
